[package]
name = "bitap"
version = "0.1.0"
edition = "2021"
authors = ["osawa naotaka <ohsawa.naotaka@gmail.com>"]
description = "bitap searcher"
license = "MIT"
repository = "https://github.com/osawa-naotaka/staticseek"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
